//
//  PollsInteractor.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 9/17/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Async
import UIKit

protocol PollsBusinessLogic {
  func populate(request: Polls.Populate.Request)
}

protocol PollsDataStore {

}

class PollsInteractor: PollsBusinessLogic, PollsDataStore {
  var presenter: PollsPresentationLogic?

  func populate(request: Polls.Populate.Request) {
    func sendLoading() {
      let response = Polls.Populate.Response(state: .loading)
      presenter?.presentPopulate(response: response)
    }

    func sendFailed(_ error: Error) {
      let response = Polls.Populate.Response(state: .failure(error))
      presenter?.presentPopulate(response: response)
    }

    sendLoading()

    PashmakServer.perform(request: ServerRequest.Polls.getPolls())
      .done { [weak self] (result: ServerData<[ServerModels.Poll.PollItem]>) in
        guard let self = self else {
          return
        }
        let polls = result.model
        Async.main(after: 2.0) {
          let response = Polls.Populate.Response(state: .success(polls))
          self.presenter?.presentPopulate(response: response)
        }
      }
      .catch { error in
        sendFailed(error)
      }

  }
}
