//
//  MessagesModels.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 9/16/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import IGListKit
import UIKit

enum Messages {

  enum Populate {
    typealias FetchMessagesState = FetchState<[ServerModels.Messages.ListItem], Error>
    struct Request {

    }
    struct Response {
      let state: FetchMessagesState
    }
    enum ViewModel {
      struct Loading {
        let items: [ListDiffable]
      }

      struct Failed {
        let message: String
      }

      struct Success {
        let items: [ListDiffable]
      }
    }
  }

}
