//
//  MessagesRouter.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 9/16/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MessagesRoutingLogic {

}

protocol MessagesDataPassing {
  var dataStore: MessagesDataStore? { get }
}

class MessagesRouter: NSObject, MessagesRoutingLogic, MessagesDataPassing {
  weak var viewController: MessagesViewController?
  var dataStore: MessagesDataStore?

}
