//
//  HomeModels.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 8/26/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import IGListKit

enum Home {
  enum Populate {
    typealias FetchHomeState = FetchState<(ServerModels.Home, Settings), Error>
    struct Request {

    }
    struct Response {
      let state: FetchHomeState
    }

    enum ViewModel {

      struct Loading {
        let message: String
      }

      struct Failed {
        let message: String
      }

      struct Success {
        let fullName: String
        let avatarURL: String
        let items: [ListDiffable]
      }

    }
  }
}
