//
//  HomeRouter.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 8/26/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Hero
import UIKit

@objc protocol HomeRoutingLogic {
func routeToLogin(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing {
  var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
  weak var viewController: HomeViewController?
  var dataStore: HomeDataStore?

  func routeToLogin(segue: UIStoryboardSegue?) {

    guard let loginVC = Storyboards.Main.instantiateViewController(withIdentifier: StoryboardsIDs.Main.Login) as? LoginViewController else {
      return
    }

    let navController = viewController?.tabBarController?.navigationController
    navController?.hero.navigationAnimationType = .zoom
    navController?.setViewControllers([loginVC], animated: true)

  }

}
