//
//  HomePresenter.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 8/26/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
func presentPopulate(response: Home.Populate.Response)
}

class HomePresenter: HomePresentationLogic {
  weak var viewController: HomeDisplayLogic?
  func presentPopulate(response: Home.Populate.Response) {

    let fullName = response.fullName
    let avatarURL = response.avatarURL
    let viewModel = Home.Populate.ViewModel.init(fullName: fullName, avatarURL: avatarURL, items: [])
    viewController?.displayPopulate(viewModel: viewModel)

  }
}
