//
//  SplashInteractor.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 8/21/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashBusinessLogic {
  func goNext(request: Splash.GoNext.Request)
}

protocol SplashDataStore {

}

class SplashInteractor: SplashBusinessLogic, SplashDataStore {
  var presenter: SplashPresentationLogic?

  func goNext(request: Splash.GoNext.Request) {

    if !Settings.current.oauthToken.isEmpty {
      let response = Splash.GoNext.Response(destination: .home)
      presenter?.presentGoNext(response: response)
    } else {
      let response = Splash.GoNext.Response(destination: .login)
      presenter?.presentGoNext(response: response)
    }

  }
}
