//
//  SplashPresenter.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 8/21/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic {
  func presentGoNext(response: Splash.GoNext.Response)
}

class SplashPresenter: SplashPresentationLogic {
  weak var viewController: SplashDisplayLogic?

  func presentGoNext(response: Splash.GoNext.Response) {
    let dest = response.destination
    let viewModel = Splash.GoNext.ViewModel(destination: dest)
    viewController?.displayGoNext(viewModel: viewModel)
  }
}
