//
//  LoginPresenter.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 8/21/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentVerify(response: Login.Verify.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  func presentVerify(response: Login.Verify.Response) {
    let phoneIsValid = response.phoneIsValid
    let idIsValid = response.nationalIdIsValid
    
    let viewModel = Login.Verify.ViewModel(phoneIsValid: phoneIsValid, nationalIdIsValid: idIsValid)
    viewController?.displayVerify(viewModel: viewModel)
  }
}
