//
//  LoginPresenter.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 8/21/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
  func presentVerify(response: Login.Verify.Response)
  func presentAuthenticate(response: Login.Authenticate.Response)
}

class LoginPresenter: LoginPresentationLogic {
  weak var viewController: LoginDisplayLogic?
  func presentVerify(response: Login.Verify.Response) {
    let phoneIsValid = response.phoneIsValid
    let idIsValid = response.nationalIdIsValid

    let viewModel = Login.Verify.ViewModel(phoneIsValid: phoneIsValid, nationalIdIsValid: idIsValid)
    viewController?.displayVerify(viewModel: viewModel)
  }

  func presentAuthenticate(response: Login.Authenticate.Response) {

    let state = response.state

    switch state {
    case .loading:
      let message = Messages.Loading.messages.randomElement() ?? ""
      let viewModel = Login.Authenticate.ViewModel.Loading.init(message: message)
      viewController?.displayAuthenticateLoading(viewModel: viewModel)
    case .failure(let error):
      var message = "نشد که بشه!"
      if case APIError.invalidParameters(_) = error {
        message = "نام کاربری و پسورد رو اشتباه زدی که!"
      } else if case APIError.invalidResponseCode(let statusCode) = error {
        if statusCode == 401 {
          message = "مشکوک به نظر میرسی 🤨🤨🤨\n این شماره و رمزی که دادی غلط از آب در اومد!"
        } else {
          message = Messages.ServerErrors.messages.randomElement() ?? message
          message += "\n(\(statusCode))"
        }

      }

      let viewModel = Login.Authenticate.ViewModel.Failed.init(message: message)
      viewController?.displayAuthenticateFailed(viewModel: viewModel)

    case .success(let response):
      let firstName = response.name ?? ""
      let lastName = response.lastName ?? ""

      var fullName = ""
      if !firstName.isEmpty {
        fullName += firstName
      }

      if !lastName.isEmpty {
        fullName += " \(lastName)"
      }
      let message = "\(fullName) خوش اومدی!"

      let viewModel = Login.Authenticate.ViewModel.Success.init(message: message)
      viewController?.displayAuthenticateSuccess(viewModel: viewModel)

    }

  }

}
