//
//  LoginRouter.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 8/21/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Hero
import UIKit

@objc protocol LoginRoutingLogic {
  func routeToHome(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing {
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?

  func routeToHome(segue: UIStoryboardSegue?) {

    guard let sourceVC = viewController, let sourceDS = dataStore else {
      return
    }

    func handleNonSegue() {

      let destVC = Storyboards.Main.instantiateViewController(withIdentifier: StoryboardsIDs.Main.Home) as? HomeViewController
      guard let destinationVC = destVC, var destinationDS = destVC?.router?.dataStore else {
        return
      }

      passDataToHome(source: sourceDS, destination: &destinationDS)
      prepareHome(source: sourceVC, destination: destinationVC)
      navigateToHome(source: sourceVC, destination: destinationVC)

    }

    guard let destinationVC = segue?.destination as? HomeViewController, var destinationDS = destinationVC.router?.dataStore else {
      handleNonSegue()
      return
    }

    passDataToHome(source: sourceDS, destination: &destinationDS)
    prepareHome(source: sourceVC, destination: destinationVC)

  }

  private func passDataToHome(source: LoginDataStore, destination: inout HomeDataStore) {

  }

  private func prepareHome(source: LoginViewController, destination: HomeViewController) {
    destination.hero.isEnabled = true
    source.navigationController?.hero.navigationAnimationType = .zoomOut
//    destination.populate()
  }

  private func navigateToHome(source: LoginViewController, destination: HomeViewController) {
    let mainTab = Storyboards.Main.instantiateViewController(withIdentifier: StoryboardsIDs.Main.MainTabbar)
    source.navigationController?.setViewControllers([mainTab], animated: true)
  }

}
