//
//  TransactionsRouter.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 9/26/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Hero
import UIKit

@objc protocol TransactionsRoutingLogic {

}

protocol TransactionsDataPassing {
  var dataStore: TransactionsDataStore? { get }
}

class TransactionsRouter: NSObject, TransactionsRoutingLogic, TransactionsDataPassing {
  weak var viewController: TransactionsViewController?
  var dataStore: TransactionsDataStore?
}
