//
//  TransactionsModels.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 9/26/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import IGListKit
import UIKit

enum Transactions {

  enum Populate {

    typealias TransactionsFetchState = FetchState<[ServerModels.Transactions.Item], Error>

    struct Request {

    }
    struct Response {
      let state: TransactionsFetchState
    }
    enum ViewModel {
      struct Loading {
        let items: [ListDiffable]
      }

      struct Failed {
        let message: String
      }

      struct Success {
        let items: [ListDiffable]
      }
    }
  }

}
