//
//  CheckinsRouter.swift
//  Pashmak
//
//  Created by Mohammad Porooshani on 9/25/18.
//  Copyright (c) 2018 Mohammad Porooshani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CheckinsRoutingLogic {

}

protocol CheckinsDataPassing {
  var dataStore: CheckinsDataStore? { get }
}

class CheckinsRouter: NSObject, CheckinsRoutingLogic, CheckinsDataPassing {
  weak var viewController: CheckinsViewController?
  var dataStore: CheckinsDataStore?

}
